# Generated by Django 6.1.1 on 2026-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_of_floreal_paris', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ')], db_index=True, default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Просмотры'),
        ),
    ]
